// Error names
module.exports = {
  PARAMS_REQUIRED: 'PARAMS_REQUIRED',
  ROOM_DOES_NOT_EXISTS: 'ROOM_DOES_NOT_EXISTS',
  ADD_ONE_PLAYER_PER_TIME: 'ADD_ONE_PLAYER_PER_TIME',
  DATABASE_ERROR: 'DATABASE_ERROR',
};
